config/routes.rb
Gamelib::Application.routes.draw do
  

  get 'join' => 'welcome#join'
  post 'join' => 'welcome#create' , :as => "create_user"

  match 'login' => 'welcome#login', :as => "log_in"
  match 'logout' => 'welcome#logout', :as => "log_out"

  resources :my_games , :as => "games"
  resources :all_games, :only => [:index] do
    collection do
      get 'search'
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :gamecopies
  has_many :users, :through => :gamecopies

  def self.search terms
      Game.where('title like :query',{:query => "%#{terms}%"})
  end
end

app/models/game_copy.rb
class GameCopy < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :gamecopies
  has_many :games, :through => :gamecopies 
 
  attr_accessor :password  
  
  before_save :encrypt_password

  validates_confirmation_of :password  
  validates_presence_of :password, :on => :create  

  validates_presence_of :email  
  validates_uniqueness_of :email  

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end

  def self.authenticate(email,password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/all_games_controller.rb
class AllGamesController < ApplicationController
  
  def index
    @games = Game.all
  end

  def search
    if params[:q]
      @games = Game.search(params[:q])
      if ( @games.count > 0)
        @searchSummary = "found #{@games.count} games matching #{params[:q]}"
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/my_games_controller.rb
class MyGamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params[:game])

    if @game.save
      redirect_to all_games_path, :notice => 'successfully created.' 
    else
      render :new
    end
  end

  


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def login
    if ( params[:email] && params[:password] )
      user = User.authenticate( params[:email] , params[:password] )
      if user  
        session[:user_id] = user.id  
        redirect_to all_games_url, :notice => "Thanks, you are logged in as #{user.email}!"  
      else  
        flash.now.alert = "Invalid email or password"  
      end  
    end
  end

  def join
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save  
      redirect_to all_games_url, :notice => "Thanks #{ @user.email }, you have been signed up!"  
    else  
      render "join"  
    end
  end


  def logout
  end

end

app/helpers/all_games_helper.rb
module AllGamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_games_helper.rb
module MyGamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/all_games/browse.html.haml
%h1 Here's all the games: 
- @games.each do |game|
  %p Title : #{game.title}

app/views/all_games/index.html.haml
%h1 Here's all the games: 
- @games.each do |game|
  %p Title : #{game.title}

app/views/all_games/search.html.haml
%h1 All Games
%form{:method => "get" }
  %input#q{:type => "text", :name => "q", :value => params[:q] || ""}
  %input{:type => "submit", :value => "search" } 
- if @games
  .results#resultsDiv
    %p
      Search Results
      -@games.each do |game|
        %p Title : #{game.title}
    %p=@searchSummary

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    <title>Gamelib</title>
    = stylesheet_link_tag :all 
    = javascript_include_tag :defaults 
    = csrf_meta_tag 
  %body
    - flash.each do |key, msg| 
      = content_tag :div, msg, :class => [key, " message"], :id => "notice_ #{key}" 
    = yield 

app/views/my_games/new.html.haml
%h1 Add a game!
= form_for @game  do |f|
  =f.label :title 
  =f.text_field :title, :id => "title" 
  %br/
  =f.label :description 
  =f.text_field :description, :id => "description"
  %br/
  =f.submit "add"
%br/
%br/
%p That's All!
  

app/views/welcome/join.html.haml
%h1 Sign Up
= form_for @user, :url => create_user_path(@user) do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :email
    %br/
    = f.text_field :email
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  %p.button= f.submit "Join"

app/views/welcome/login.html.haml
%h1 Log In
= form_tag log_in_path do
  %p
    = label_tag :email
    = text_field_tag :email, params[:email]
  %p
    = label_tag :password
    = password_field_tag :password, params[:password]
  %p.button=submit_tag "login" 

app/views/welcome/logout.html.haml
%h1 Thanks for visiting, you are now signed out